// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi2TmIRqNozE5g4kUQwdIdhC63wMX3sbU',
    appId: '1:689534840988:web:fc620ba1d956b309d9bd59',
    messagingSenderId: '689534840988',
    projectId: 'testing-c49a7',
    authDomain: 'testing-c49a7.firebaseapp.com',
    storageBucket: 'testing-c49a7.appspot.com',
    measurementId: 'G-2KY5KR5DH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1KnssdzvIc49OvdnnH84uZRNTxVyqqbg',
    appId: '1:689534840988:android:428158c3a86b230dd9bd59',
    messagingSenderId: '689534840988',
    projectId: 'testing-c49a7',
    storageBucket: 'testing-c49a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkZfrRluv2D7laakuh0eMLSGJJd3wAE00',
    appId: '1:689534840988:ios:09a2fa667d8a9b64d9bd59',
    messagingSenderId: '689534840988',
    projectId: 'testing-c49a7',
    storageBucket: 'testing-c49a7.appspot.com',
    iosBundleId: 'com.example.firebasePractise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkZfrRluv2D7laakuh0eMLSGJJd3wAE00',
    appId: '1:689534840988:ios:09a2fa667d8a9b64d9bd59',
    messagingSenderId: '689534840988',
    projectId: 'testing-c49a7',
    storageBucket: 'testing-c49a7.appspot.com',
    iosBundleId: 'com.example.firebasePractise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi2TmIRqNozE5g4kUQwdIdhC63wMX3sbU',
    appId: '1:689534840988:web:3a6cd3f34fffcf5ed9bd59',
    messagingSenderId: '689534840988',
    projectId: 'testing-c49a7',
    authDomain: 'testing-c49a7.firebaseapp.com',
    storageBucket: 'testing-c49a7.appspot.com',
    measurementId: 'G-HVLB11VBEP',
  );
}
